// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_rider/test/modules/auth/presentation/login/view_model/cubit/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_rider/config/base_response/base_response.dart' as _i4;
import 'package:flowery_rider/modules/auth/data/models/request/login_request.dart'
    as _i6;
import 'package:flowery_rider/modules/auth/domain/entities/login_response_entity.dart'
    as _i5;
import 'package:flowery_rider/modules/auth/domain/use_cases/login_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i2.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.LoginResponseEntity>> call({
    required _i6.LoginRequest? body,
    required bool? isRememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #body: body,
              #isRememberMe: isRememberMe,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.LoginResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #body: body,
                      #isRememberMe: isRememberMe,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.LoginResponseEntity>>);
}
