workflows:
  flutter-shared-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate Code (Build Runner)
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
    publishing:
      firebase:
        app_id: "1:195057298331:android:befe11f83ac5496d740f3e"
        token: "1//092WviAP8R3xHCgYIARAAGAkSNwF-L9IrXPUix876Ailv3yAuJ_k5W6SilavgCcJJAJJ4pf-9wbJpjZCJltQZIn0nAYrMfWuBXuM"
        testers:
          - khalidadel365@gmail.com