// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_rider/test/features/order_tracking/data/repositories/order_tracking_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_rider/config/base_response/base_response.dart' as _i4;
import 'package:flowery_rider/features/order_tracking/data/models/request/update_order_state_request.dart'
    as _i8;
import 'package:flowery_rider/features/order_tracking/data/models/response/order_dto.dart'
    as _i9;
import 'package:flowery_rider/features/order_tracking/data/models/response/pending_orders_dto.dart'
    as _i5;
import 'package:flowery_rider/features/order_tracking/data/models/response/start_order_dto/orders_state_response_dto.dart'
    as _i7;
import 'package:flowery_rider/features/order_tracking/data/remote/data_sources/order_tracking_remote_data_source_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderTrackingRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingRemoteDataSourceContract extends _i1.Mock
    implements _i2.OrderTrackingRemoteDataSourceContract {
  MockOrderTrackingRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.PendingOrdersDto>> getPendingOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOrders, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.PendingOrdersDto>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.PendingOrdersDto>>(
                    this,
                    Invocation.method(#getPendingOrders, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.PendingOrdersDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>> updateOrderState(
    String? orderId,
    _i8.UpdateOrderStateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [orderId, request]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.OrderStateResponseDto>>(
                    this,
                    Invocation.method(#updateOrderState, [orderId, request]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>> startOrder(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.OrderStateResponseDto>>(
                    this,
                    Invocation.method(#startOrder, [orderId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.OrderStateResponseDto>>);

  @override
  _i3.Future<void> saveOrderToFirestore(
    String? orderId,
    _i9.OrderDto? order,
    String? driverId,
    String? driverName,
    String? driverPhone,
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrderToFirestore, [
              orderId,
              order,
              driverId,
              driverName,
              driverPhone,
              lat,
              lng,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDriverLocationInFirestore(
    String? orderId,
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDriverLocationInFirestore, [
              orderId,
              lat,
              lng,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOrderStatusInFirestore(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatusInFirestore, [orderId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<String?> getOrderStatusStream(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusStream, [orderId]),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Future<_i9.OrderDto?> getActiveOrderFromFirestore(String? driverId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrderFromFirestore, [driverId]),
            returnValue: _i3.Future<_i9.OrderDto?>.value(),
          )
          as _i3.Future<_i9.OrderDto?>);
}
