// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_rider/test/features/order_tracking/data/remote/data_sources/order_tracking_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowery_rider/modules/order_tracking/data/models/request/update_order_state_request.dart'
    as _i7;
import 'package:flowery_rider/modules/order_tracking/data/models/response/driver_orders_response_model.dart'
    as _i4;
import 'package:flowery_rider/modules/order_tracking/data/models/response/pending_orders_dto.dart'
    as _i2;
import 'package:flowery_rider/modules/order_tracking/data/models/response/start_order_dto/orders_state_response_dto.dart'
    as _i3;
import 'package:flowery_rider/modules/order_tracking/data/remote/api_client/order_tracking_api_client.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePendingOrdersDto_0 extends _i1.SmartFake
    implements _i2.PendingOrdersDto {
  _FakePendingOrdersDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderStateResponseDto_1 extends _i1.SmartFake
    implements _i3.OrderStateResponseDto {
  _FakeOrderStateResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriverOrdersResponseModel_2 extends _i1.SmartFake
    implements _i4.DriverOrdersResponseModel {
  _FakeDriverOrdersResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderTrackingApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingApiClient extends _i1.Mock
    implements _i5.OrderTrackingApiClient {
  MockOrderTrackingApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PendingOrdersDto> getPendingOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOrders, []),
            returnValue: _i6.Future<_i2.PendingOrdersDto>.value(
              _FakePendingOrdersDto_0(
                this,
                Invocation.method(#getPendingOrders, []),
              ),
            ),
          )
          as _i6.Future<_i2.PendingOrdersDto>);

  @override
  _i6.Future<_i3.OrderStateResponseDto> updateOrderState(
    String? orderId,
    _i7.UpdateOrderStateRequest? updateOrderStateRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [
              orderId,
              updateOrderStateRequest,
            ]),
            returnValue: _i6.Future<_i3.OrderStateResponseDto>.value(
              _FakeOrderStateResponseDto_1(
                this,
                Invocation.method(#updateOrderState, [
                  orderId,
                  updateOrderStateRequest,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.OrderStateResponseDto>);

  @override
  _i6.Future<_i3.OrderStateResponseDto> startOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i6.Future<_i3.OrderStateResponseDto>.value(
              _FakeOrderStateResponseDto_1(
                this,
                Invocation.method(#startOrder, [orderId]),
              ),
            ),
          )
          as _i6.Future<_i3.OrderStateResponseDto>);

  @override
  _i6.Future<_i4.DriverOrdersResponseModel> getAllDriverOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDriverOrders, []),
            returnValue: _i6.Future<_i4.DriverOrdersResponseModel>.value(
              _FakeDriverOrdersResponseModel_2(
                this,
                Invocation.method(#getAllDriverOrders, []),
              ),
            ),
          )
          as _i6.Future<_i4.DriverOrdersResponseModel>);
}
