// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdn4Z6vmvY3h3lMy-EX-8gU_IbcD0Rs4',
    appId: '1:195057298331:web:07538229d18e596e740f3e',
    messagingSenderId: '195057298331',
    projectId: 'flower-app-be078',
    authDomain: 'flower-app-be078.firebaseapp.com',
    storageBucket: 'flower-app-be078.firebasestorage.app',
    measurementId: 'G-NBN6QNZQKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf72WoTeWRF6aB02xZEijdbcsKaBdeGx4',
    appId: '1:195057298331:android:39c542ce08c853ca740f3e',
    messagingSenderId: '195057298331',
    projectId: 'flower-app-be078',
    storageBucket: 'flower-app-be078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9FkXIwfEa9Qzkf5rwJ074aKMTRxj-e4',
    appId: '1:195057298331:ios:e36a2a985daebdd1740f3e',
    messagingSenderId: '195057298331',
    projectId: 'flower-app-be078',
    storageBucket: 'flower-app-be078.firebasestorage.app',
    iosBundleId: 'com.example.floweryRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9FkXIwfEa9Qzkf5rwJ074aKMTRxj-e4',
    appId: '1:195057298331:ios:e36a2a985daebdd1740f3e',
    messagingSenderId: '195057298331',
    projectId: 'flower-app-be078',
    storageBucket: 'flower-app-be078.firebasestorage.app',
    iosBundleId: 'com.example.floweryRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqdn4Z6vmvY3h3lMy-EX-8gU_IbcD0Rs4',
    appId: '1:195057298331:web:e4a23c66f6894a52740f3e',
    messagingSenderId: '195057298331',
    projectId: 'flower-app-be078',
    authDomain: 'flower-app-be078.firebaseapp.com',
    storageBucket: 'flower-app-be078.firebasestorage.app',
    measurementId: 'G-F3DLB6F7S3',
  );
}
