// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_rider/test/modules/auth/data/remote/data_sources/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i8;
import 'package:flowery_rider/modules/auth/data/models/request/login_request.dart'
    as _i7;
import 'package:flowery_rider/modules/auth/data/models/response/apply_response_model.dart'
    as _i4;
import 'package:flowery_rider/modules/auth/data/models/response/login_response_dto.dart'
    as _i2;
import 'package:flowery_rider/modules/auth/data/models/response/logout_response_dto.dart'
    as _i3;
import 'package:flowery_rider/modules/auth/data/remote/api_client/auth_api_client.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogOutResponseDto_1 extends _i1.SmartFake
    implements _i3.LogOutResponseDto {
  _FakeLogOutResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponseModel_2 extends _i1.SmartFake
    implements _i4.ApplyResponseModel {
  _FakeApplyResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i5.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.LoginResponseDto> login({required _i7.LoginRequest? body}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#body: body}),
            returnValue: _i6.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [], {#body: body}),
              ),
            ),
          )
          as _i6.Future<_i2.LoginResponseDto>);

  @override
  _i6.Future<_i3.LogOutResponseDto> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<_i3.LogOutResponseDto>.value(
              _FakeLogOutResponseDto_1(this, Invocation.method(#logout, [])),
            ),
          )
          as _i6.Future<_i3.LogOutResponseDto>);

  @override
  _i6.Future<_i4.ApplyResponseModel> applyAsDriver(_i8.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#applyAsDriver, [formData]),
            returnValue: _i6.Future<_i4.ApplyResponseModel>.value(
              _FakeApplyResponseModel_2(
                this,
                Invocation.method(#applyAsDriver, [formData]),
              ),
            ),
          )
          as _i6.Future<_i4.ApplyResponseModel>);
}
