// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_rider/test/features/order_tracking/presentation/home/view_model/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_rider/config/base_response/base_response.dart' as _i4;
import 'package:flowery_rider/core/services/location_service.dart' as _i11;
import 'package:flowery_rider/modules/order_tracking/domain/entities/response/order_entity.dart'
    as _i10;
import 'package:flowery_rider/modules/order_tracking/domain/entities/response/order_state_entities/order_state_response_entity.dart'
    as _i8;
import 'package:flowery_rider/modules/order_tracking/domain/entities/response/pending_orders_entity.dart'
    as _i5;
import 'package:flowery_rider/modules/order_tracking/domain/use_cases/firestore_order_use_case.dart'
    as _i9;
import 'package:flowery_rider/modules/order_tracking/domain/use_cases/get_pending_orders_use_case.dart'
    as _i2;
import 'package:flowery_rider/modules/order_tracking/domain/use_cases/start_order_use_case.dart'
    as _i7;
import 'package:geolocator/geolocator.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetPendingOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingOrdersUseCase extends _i1.Mock
    implements _i2.GetPendingOrdersUseCase {
  MockGetPendingOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.PendingOrdersEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.PendingOrdersEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.PendingOrdersEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.PendingOrdersEntity>>);
}

/// A class which mocks [StartOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartOrderUseCase extends _i1.Mock implements _i7.StartOrderUseCase {
  MockStartOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i8.OrderStateResponseEntity>> call(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [orderId]),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i8.OrderStateResponseEntity>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i8.OrderStateResponseEntity>
                  >(this, Invocation.method(#call, [orderId])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.OrderStateResponseEntity>>);
}

/// A class which mocks [FirestoreOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreOrderUseCase extends _i1.Mock
    implements _i9.FirestoreOrderUseCase {
  MockFirestoreOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveOrder(
    String? orderId,
    _i10.OrderEntity? order,
    String? driverId,
    String? driverName,
    String? driverPhone,
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrder, [
              orderId,
              order,
              driverId,
              driverName,
              driverPhone,
              lat,
              lng,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLocation(String? orderId, double? lat, double? lng) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [orderId, lat, lng]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatus(String? orderId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [orderId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<String?> getOrderStatusStream(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusStream, [orderId]),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Future<_i10.OrderEntity?> getActiveOrder(String? driverId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrder, [driverId]),
            returnValue: _i3.Future<_i10.OrderEntity?>.value(),
          )
          as _i3.Future<_i10.OrderEntity?>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i11.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> handleLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#handleLocationPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i12.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<_i12.Position?>.value(),
          )
          as _i3.Future<_i12.Position?>);
}
